name: Deploy Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          cd backend
          npm install
      - name: Run Tests (optional)
        run: echo "No tests yet"
      - name: Deploy to Server (e.g., Render, Railway, or self-hosted)
        run: echo "Add SSH/Rsync/Deploy logic here"
